import { expect, test } from "@playwright/test";

/**
 * Utility / metadata routes — robots, sitemap, OG image, auth
 * provider catalogue. These don't render visible UI but absolutely
 * matter for SEO, social previews, and login wiring.
 */

test("utility: /robots.txt is served", async ({ request }) => {
  const r = await request.get("/robots.txt");
  expect(r.status()).toBe(200);
  const text = await r.text();
  expect(text).toContain("User-Agent");
  expect(text).toContain("Sitemap");
});

test("utility: /sitemap.xml lists at least the homepage", async ({ request }) => {
  const r = await request.get("/sitemap.xml");
  expect(r.status()).toBe(200);
  const xml = await r.text();
  expect(xml.startsWith("<?xml")).toBeTruthy();
  // The site URL from `metadataBase` is the canonical homepage entry.
  expect(xml).toMatch(/<loc>https?:\/\/[^<]+<\/loc>/);
});

test("utility: /opengraph-image.png is a PNG", async ({ request }) => {
  // `app/opengraph-image.png` is served at this path by Next 16 (or
  // generated by `app/opengraph-image.tsx`). Either way the response
  // should be a real image, not a 404 / HTML error page.
  const r = await request.get("/opengraph-image.png");
  expect(r.status()).toBeLessThan(400);
  const ct = r.headers()["content-type"] ?? "";
  expect(ct).toMatch(/image\//);
});

test("utility: NextAuth providers endpoint returns JSON", async ({ request }) => {
  const r = await request.get("/api/auth/providers");
  expect(r.status()).toBe(200);
  const json = await r.json();
  // We only configure the MusicBrainz provider — if that goes missing,
  // the login button breaks silently. Catch it here.
  expect(typeof json).toBe("object");
  expect(Object.keys(json).length).toBeGreaterThan(0);
});
