import Link from "next/link";
import { Globe, Tag, User } from "lucide-react";
import { modeLabel, type RadioMode } from "@/lib/radio-modes";
import { RadioModeSlider } from "./radio-mode-slider";

/** Best-effort classification of a preset prompt for the chip icon.
 *  When a prompt mixes kinds (e.g. `country:(spain) tag:(indie)`),
 *  pick the most specific signal — artist beats country beats tag —
 *  so the icon matches the dimension that *defines* the station. */
type PresetKind = "artist" | "country" | "tag";
function presetKind(prompt: string): PresetKind {
  if (/\bartist:\(/i.test(prompt)) return "artist";
  if (/\bcountry:\(/i.test(prompt)) return "country";
  return "tag";
}

function PresetIcon({ kind }: { kind: PresetKind }) {
  const Icon = kind === "artist" ? User : kind === "country" ? Globe : Tag;
  return <Icon className="text-muted-foreground/80 size-3 shrink-0" />;
}

export type { RadioMode };

interface PresetExample {
  label: string;
  prompt: string;
  mode: RadioMode;
}

const PRESETS: PresetExample[] = [
  { label: "Shoegaze", prompt: "tag:(shoegaze)", mode: "easy" },
  {
    label: "Dream pop & ambient",
    prompt: "tag:(dream pop, ambient)",
    mode: "medium",
  },
  { label: "Post-punk revival", prompt: "tag:(post-punk)", mode: "easy" },
  {
    label: "Spanish-language indie",
    prompt: "country:(spain) tag:(indie)",
    mode: "medium",
  },
  { label: "Krautrock", prompt: "tag:(krautrock)", mode: "hard" },
  { label: "Cool jazz", prompt: "tag:(cool jazz)", mode: "easy" },
  // Artist-by-name presets exercise the MB resolution path —
  // helpful as a discoverability hint, since the placeholder
  // already mentions `artist:(Alex G)`.
  { label: "Alex G", prompt: "artist:(Alex G)", mode: "easy" },
  { label: "Big Thief", prompt: "artist:(Big Thief)", mode: "medium" },
];

function presetHref(p: PresetExample): string {
  const params = new URLSearchParams({ prompt: p.prompt, mode: p.mode });
  return `/radio/builder?${params}`;
}

export function StationBuilder({
  prompt = "",
  mode = "easy",
}: {
  prompt?: string;
  mode?: RadioMode;
}) {
  return (
    <section className="space-y-6">
      <form
        action="/radio/builder"
        method="get"
        className="border-border/60 bg-card/40 space-y-4 rounded-2xl border p-5"
      >
        <div>
          <label
            htmlFor="prompt"
            className="text-foreground text-sm font-medium"
          >
            Station prompt
          </label>

          {/* Mode picker sits right under the section header so it
              reads as a "what kind of station" pre-amble before the
              user types into the prompt input below.
              Key on the URL mode so the slider's local state resets
              when navigating in via a preset chip — useState's
              initial value only fires on mount, so without the key a
              preset-driven mode change wouldn't move the slider. */}
          <div className="mt-3">
            <RadioModeSlider key={mode} initialMode={mode} />
          </div>

          <p className="text-muted-foreground mt-3 text-xs leading-5">
            What should it play? Try a genre like{" "}
            <code className="bg-muted/70 rounded px-1 py-0.5">tag:(jazz)</code>,
            an artist by name like{" "}
            <code className="bg-muted/70 rounded px-1 py-0.5">
              artist:(Alex G)
            </code>
            , or music from a country like{" "}
            <code className="bg-muted/70 rounded px-1 py-0.5">
              country:(spain)
            </code>
            . Mix them with spaces — or just pick one of the examples below.
          </p>
          <input
            id="prompt"
            name="prompt"
            type="text"
            required
            placeholder="tag:(shoegaze) or artist:(Alex G)"
            defaultValue={prompt}
            className="border-border/60 bg-background placeholder:text-muted-foreground/70 focus:ring-ring/30 mt-3 h-11 w-full rounded-lg border px-3 text-sm outline-none focus:ring-2"
          />
        </div>

        <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
          <p className="text-muted-foreground/70 text-xs">
            Stations are generated by ListenBrainz Radio. Hit play in
            Parachord to listen along.
          </p>
          <button
            type="submit"
            className="bg-primary text-primary-foreground inline-flex h-9 items-center gap-2 rounded-lg px-4 text-sm font-medium transition-opacity hover:opacity-90"
          >
            Build station
          </button>
        </div>
      </form>

      <div>
        <p className="text-muted-foreground/80 text-xs tracking-wide uppercase">
          Try one
        </p>
        <ul className="mt-2 flex flex-wrap gap-2">
          {PRESETS.map((p) => (
            <li key={`${p.prompt}-${p.mode}`}>
              <Link
                href={presetHref(p)}
                className="border-border/60 hover:border-foreground/40 hover:bg-muted/40 inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs transition-colors"
              >
                <PresetIcon kind={presetKind(p.prompt)} />
                <span className="text-foreground">{p.label}</span>
                <span className="text-muted-foreground/70 hidden sm:inline">
                  · {modeLabel(p.mode)}
                </span>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}
