import Link from "next/link";

const MODES = [
  {
    id: "easy" as const,
    label: "Easy",
    blurb: "Stay close — tracks similar to the seed.",
  },
  {
    id: "medium" as const,
    label: "Medium",
    blurb: "Mix it up — adjacent artists and styles.",
  },
  {
    id: "hard" as const,
    label: "Hard",
    blurb: "Wide net — bigger jumps from the seed.",
  },
] as const;

export type RadioMode = (typeof MODES)[number]["id"];

interface PresetExample {
  label: string;
  prompt: string;
  mode: RadioMode;
}

const PRESETS: PresetExample[] = [
  { label: "Shoegaze", prompt: "tag:(shoegaze)", mode: "easy" },
  {
    label: "Dream pop & ambient",
    prompt: "tag:(dream pop, ambient)",
    mode: "medium",
  },
  { label: "Post-punk revival", prompt: "tag:(post-punk)", mode: "easy" },
  {
    label: "Spanish-language indie",
    prompt: "country:(spain) tag:(indie)",
    mode: "medium",
  },
  { label: "Krautrock", prompt: "tag:(krautrock)", mode: "hard" },
  { label: "Cool jazz", prompt: "tag:(cool jazz)", mode: "easy" },
];

function presetHref(p: PresetExample): string {
  const params = new URLSearchParams({ prompt: p.prompt, mode: p.mode });
  return `/radio/builder?${params}`;
}

export function StationBuilder({
  prompt = "",
  mode = "easy",
}: {
  prompt?: string;
  mode?: RadioMode;
}) {
  return (
    <section className="space-y-6">
      <form
        action="/radio/builder"
        method="get"
        className="border-border/60 bg-card/40 space-y-4 rounded-2xl border p-5"
      >
        <div>
          <label
            htmlFor="prompt"
            className="text-foreground text-sm font-medium"
          >
            Station prompt
          </label>
          <p className="text-muted-foreground mt-1 text-xs leading-5">
            ListenBrainz Radio takes a small DSL — common building blocks:{" "}
            <code className="bg-muted/70 rounded px-1 py-0.5">tag:(jazz)</code>,{" "}
            <code className="bg-muted/70 rounded px-1 py-0.5">
              artist:(&lt;mbid&gt;)
            </code>
            ,{" "}
            <code className="bg-muted/70 rounded px-1 py-0.5">
              country:(spain)
            </code>
            . Combine with spaces.
          </p>
          <input
            id="prompt"
            name="prompt"
            type="text"
            required
            placeholder="tag:(shoegaze) or artist:(b95ce3ff-3d05-4e87-9e01-c97b66af13d4)"
            defaultValue={prompt}
            className="border-border/60 bg-background placeholder:text-muted-foreground/70 focus:ring-ring/30 mt-3 h-11 w-full rounded-lg border px-3 text-sm outline-none focus:ring-2"
          />
        </div>

        <fieldset>
          <legend className="text-foreground text-sm font-medium">
            Mode
          </legend>
          <div
            className="mt-3 grid gap-2 sm:grid-cols-3"
            role="radiogroup"
            aria-label="Mode"
          >
            {MODES.map((m) => (
              <label
                key={m.id}
                className="border-border/60 has-[:checked]:bg-muted/40 has-[:checked]:border-foreground/40 hover:border-foreground/30 flex cursor-pointer flex-col gap-1 rounded-xl border px-3 py-2.5 transition-colors"
              >
                <input
                  type="radio"
                  name="mode"
                  value={m.id}
                  defaultChecked={m.id === mode}
                  className="sr-only"
                />
                <span className="text-foreground text-sm font-medium">
                  {m.label}
                </span>
                <span className="text-muted-foreground text-xs leading-4">
                  {m.blurb}
                </span>
              </label>
            ))}
          </div>
        </fieldset>

        <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
          <p className="text-muted-foreground/70 text-xs">
            Stations are generated by ListenBrainz Radio. Hit play in
            Parachord to listen along.
          </p>
          <button
            type="submit"
            className="bg-primary text-primary-foreground inline-flex h-9 items-center gap-2 rounded-lg px-4 text-sm font-medium transition-opacity hover:opacity-90"
          >
            Build station
          </button>
        </div>
      </form>

      <div>
        <p className="text-muted-foreground/80 text-xs tracking-wide uppercase">
          Try one
        </p>
        <ul className="mt-2 flex flex-wrap gap-2">
          {PRESETS.map((p) => (
            <li key={`${p.prompt}-${p.mode}`}>
              <Link
                href={presetHref(p)}
                className="border-border/60 hover:border-foreground/40 hover:bg-muted/40 inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs transition-colors"
              >
                <span className="text-foreground">{p.label}</span>
                <span className="text-muted-foreground/70 hidden sm:inline">
                  · {p.mode}
                </span>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </section>
  );
}
